### ISSUE TITLE
BUG: "Follow" button is not working

### ISSUE THREAD

**Issue by Anwishta** [SwanandD121/FeatherPerfect_fe#61]
**Description:**  
The Follow button on the home page is not functioning as expected. Clicking the button does not trigger any response or action.

**Steps to Reproduce:**
1. Go to the home page.
2. Click on the follow button.
3. Observe that there is no change or response.

**Expected Behavior:**  
Clicking the follow button should increase the number of people count in following section of user profile.

**Actual Behavior:**  
No response occurs when clicking the button.

**Screenshots:**  

![Screenshot 2024-10-05 184201](https://github.com/user-attachments/assets/6fc6a5c6-e126-41fb-b117-2ccf69351a49)

It would be great if you could assign me this issue under the GSSoC-ext and Hacktoberfest labels. I am excited about the opportunity to work on this and look forward to contributing.

**Comment by lakshmirajvagu** [comment]
i would like to work on it please assign me @SwanandD121

**Comment by harshbhar0629** [comment]
@SwanandD121 For last 4-days this issue is not being resolved please assign to me i will resolve this issue today for sure:)

**Comment by samyakmaitre** [comment]
Hi @harshbhar0629, @Anwishta,

This issue was assigned to @Anwishta four days ago. Please refrain from creating a PR without being assigned the issue, as it causes confusion for the admin. We are already managing 100 other issues and PRs. I hope you understand, and kindly follow the contribution rules.

@Anwishta, a response is expected regarding your inactivity. If we do not receive a reply soon, we will have to reassign this issue.

Thank you!

**Comment by harshbhar0629** [comment]
OK!

**Comment by Anwishta** [comment]
@samyakmaitre I've almost finished it. I'll make a PR today.

**Comment by SwanandD121** [comment]
merged
